# Stage 1: Build
FROM maven:3.9.8-eclipse-temurin-21 as build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Stage 2: Run
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

# Copy the JAR file from the build stage
COPY --from=build /app/target/smarthome-server-0.0.1-SNAPSHOT.jar ./app.jar

RUN adduser -D smarthome
USER smarthome

EXPOSE 8080

ENV JAVA_OPTS="-Xmx2048m -Xms256m"

# Run the application
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app/app.jar"]