server:
  port: ${PORT}
  servlet:
    context-path: /api/v1

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: smarthome-server
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            user-info-uri: "https://www.googleapis.com/oauth2/v3/userinfo"
  #            resource-server:
  #              opaque-token:
  #                introspection-uri: "https://www.googleapis.com"
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

app:
  verification-code-expiration-minutes: 15

mqtt:
  host: ${MQTT_HOST}
  port: ${MQTT_PORT}
  username: my_mqtt
  password: hellomqtt
  topic:
    device: "device_control"
    homepod: "homePod/123"
  homeId: 675d1648a9e8034a78b32495

encrypt:
  secret: ${ENCRYPT_SECRET}

jwt:
  secret: ${JWT_SECRET}
  expire: ${JWT_EXPIRE}

socket-server:
  port: 8081
  host: 0.0.0.0