server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: smarthome-server
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://hieptram40:123@cluster0.02rer4y.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0}
      database: ${MONGODB_DATABASE:smarthome-iot}

mqtt:
  host: "897e4e4bd28b411ba2464a4019281121.s1.eu.hivemq.cloud"
  port: 8883
  username: my_mqtt
  password: hellomqtt
  topic:
    device: "device_control"
    homepod: "homePod/123"
  homeId: 675d1648a9e8034a78b32495

jwt:
  secret: ${JWT_SECRET:e54c785247bbe95014719bbf1fd494ff3ada0c854d333e0d8ee0af418e237ce1349146558ffe96a262fd2fb077821665c54986a4349491cd07689d39ee07e4f8}
  expire: ${JWT_EXPIRE:1209600000}

socket-server:
  port: 8081
  host: 0.0.0.0
