server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: smarthome-server
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://hieptram40:123@cluster0.02rer4y.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0}
      database: ${MONGODB_DATABASE:smarthome-iot}

mqtt:
  host: "897e4e4bd28b411ba2464a4019281121.s1.eu.hivemq.cloud"
  port: 8883
  username: my_mqtt
  password: hellomqtt
  device:
    topic: "device_control"
  homeId: 675d1648a9e8034a78b32495

socket-server:
  port: 8081
  host: 0.0.0.0
